alter session set "_oracle_script"=TRUE;

create tablespace GYM_TABLESPACE
    datafile 'C:\USERS\JUANP\DOCUMENTS\DBGYM\DATAFILE\GYM_TABLESPACE.DBF' size 6400K autoextend ON next 1280K maxsize 33554416K
    blocksize 8 K
    logging
    online
    extent management local
    segment space management auto;

CREATE USER SCHEMA_GYM IDENTIFIED BY root;
GRANT UNLIMITED TABLESPACE TO SCHEMA_GYM;
ALTER USER SCHEMA_GYM DEFAULT TABLESPACE GYM_TABLESPACE TEMPORARY TABLESPACE TEMP;

GRANT CONNECT, RESOURCE TO SCHEMA_GYM;  --Permite conexiones de otros usuarios
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE TO SCHEMA_GYM;
GRANT CREATE USER, ALTER USER TO SCHEMA_GYM;
GRANT ALTER ANY TABLE, DROP ANY TABLE, ALTER ANY PROCEDURE, DROP ANY PROCEDURE TO SCHEMA_GYM;