--Instancias minimas para el funcionamiento de un gimnacio

INSERT INTO LUGARES (ID, PAIS, REGION, CIUDAD, DIRECCION, DETALLES, CODIGOPOSTAL)
VALUES (10, 'Colombia', 'Cundinamarca', 'Bogota', 'Avenida Jimenez 2-10', 'Centro Cultural Gabriel Garcia Marquez',
        '110011');

INSERT INTO SEDES (ID, NOMBRE, UBICACION)
VALUES (1, 'GymLaPapa', 10);

INSERT INTO ZONAS (NOMBRE, SEDE, DESCRIPCION)
VALUES ('Zona Principal', 1, 'Zona General');
INSERT INTO ZONAS (NOMBRE, SEDE, DESCRIPCION)
VALUES ('Zona Piscina', 1, 'Zona con Piscina de 50000L');

INSERT INTO TIPOMEMBRESIA (TIPO, PRECIO, DURACIONDIAS, DESCRIPCION)
VALUES ('Basica', 50000.00, 30, 'Descripción de Membresia Basica');
INSERT INTO TIPOMEMBRESIA (TIPO, PRECIO, DURACIONDIAS, DESCRIPCION)
VALUES ('BasicaPiscina', 75000.00, 45, 'Descripción de Membresia BasicaPiscina');

INSERT INTO BENEFICIOSEDES (TIPO_MEMBRESIA, SEDE, DESCRIPCION)
VALUES ('Basica', 1, 'Descripcion');
INSERT INTO BENEFICIOSEDES (TIPO_MEMBRESIA, SEDE, DESCRIPCION)
VALUES ('BasicaPiscina', 1, 'Descripcion');

INSERT INTO BENEFICIOZONAS (TIPO_MEMBRESIA, ZONA, SEDE, DESCRIPCION)
VALUES ('Basica', 'Zona Principal', 1, 'Descripcion');
INSERT INTO BENEFICIOZONAS (TIPO_MEMBRESIA, ZONA, SEDE, DESCRIPCION)
VALUES ('BasicaPiscina', 'Zona Piscina', 1, 'Descripcion');

INSERT INTO EMPLEADOS (DOCUMENTO, TIPODOCUMENTO, CORREO, TELEFONO, FECHANACIMIENTO, NOMBRE, APELLIDO, GENERO, EDAD,
                       SEDE, ESTATUS, CARGO)
VALUES (100000000, 'Cedula', 'juanperez@gmail.com', '3000123456', DATE '2000-01-01', 'Juan', 'Perez', 'Masculino', 23,
        1, 'Activo', 'Operador');
INSERT INTO EMPLEADOS (DOCUMENTO, TIPODOCUMENTO, CORREO, TELEFONO, FECHANACIMIENTO, NOMBRE, APELLIDO, GENERO, EDAD,
                       SEDE, ESTATUS, CARGO)
VALUES (1000000002, 'Pasaporte', 'marialopez@hotmail.com', '3111234567', DATE '1999-02-02', 'Maria', 'Lopez',
        'Femenino', 24, 1, 'Activo', 'Entrenador');

INSERT INTO CONTRATOS (ID, EMPLEADO, TIPOCONTRATO, FECHAINICIO, FECHAFINAL, SUELDO, DESCRIPCION, ESTADO)
VALUES (1, 100000000, 'Fijo', DATE '2023-01-01', DATE '2024-01-01', 1230000.10, 'descripcion', 'Activo');
INSERT INTO CONTRATOS (ID, EMPLEADO, TIPOCONTRATO, FECHAINICIO, FECHAFINAL, SUELDO, DESCRIPCION, ESTADO)
VALUES (2, 1000000002, 'Indefinido', DATE '2022-01-01', null, 123000.10, 'descripcion2', 'Activo');

-- Final de las instancias minimas

INSERT INTO USUARIOS (DOCUMENTO, TIPODOCUMENTO, CORREO, TELEFONO, FECHANACIMIENTO, NOMBRE, APELLIDO, GENERO, EDAD)
VALUES (12345678901234, 'Cedula', 'juan.camargo@gmail.com', 3113732948, DATE '2000-12-23', 'Juan Camargo',
        'Pablo Teheran', 'Masculino', 21);

INSERT INTO MEMBRESIAS (ID, USUARIO, TIPO, FACTURA, ESTATUS, METODOPAGO, FECHAINICIO, FECHAFINAL)
VALUES (0, 12345678901234, 'Basica', 0, 'Activo', 'PSE', DATE '2023-01-01', DATE '2023-02-02');
