CREATE PACKAGE ADMINISTRACION.PKG_ADMINISTRACION AS
    -- CRUD ZONAS
    PROCEDURE ADMINISTRACION.REGISTRAR_ZONA(
        P_NOMBRE      IN VARCHAR2,
        P_SEDE        IN NUMBER,
        P_DESCRIPCION IN VARCHAR2
    );

    FUNCTION ADMINISTRACION.OBTENER_ZONAS RETURN SYS_REFCURSOR;
    FUNCTION ADMINISTRACION.OBTENER_ZONA(P_NOMBRE IN VARCHAR2) RETURN SYS_REFCURSOR;
    FUNCTION ADMINISTRACION.OBTENER_ZONAS_SEDE(P_SEDE IN NUMBER) RETURN SYS_REFCURSOR;

    PROCEDURE ADMINISTRACION.ACTUALIZAR_ZONA(
        P_NOMBRE      IN VARCHAR2,
        P_SEDE        IN NUMBER,
        P_DESCRIPCION IN VARCHAR2
    );

    PROCEDURE ADMINISTRACION.ELIMINAR_ZONA(P_NOMBRE IN VARCHAR2, P_SEDE IN NUMBER);

    -- CRU SOLICITUDES
    PROCEDURE ADMINISTRACION.REGISTRAR_SOLICITUD(
        P_CREADOR     IN NUMBER,
        P_IMPORTANCIA IN NUMBER,
        P_ASUNTO      IN VARCHAR2,
        P_DESCRIPCION IN VARCHAR2
    );

    FUNCTION ADMINISTRACION.OBTENER_SOLICITUDES RETURN SYS_REFCURSOR;
    FUNCTION ADMINISTRACION.OBTENER_SOLICITUD(P_ID IN NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION ADMINISTRACION.OBTENER_SOLICITUDES_CREADOR(P_CREADOR IN NUMBER) RETURN SYS_REFCURSOR;

    PROCEDURE ADMINISTRACION.ACTUALIZAR_SOLICITUD(
        P_ID          IN NUMBER,
        P_IMPORTANCIA IN NUMBER,
        P_ESTADO      IN VARCHAR2,
        P_DESCRIPCION IN VARCHAR2
    );

    -- CRUD INVENTARIO
    PROCEDURE ADMINISTRACION.REGISTRAR_INVENTARIO(
        P_SEDE        IN NUMBER,
        P_NOMBRE      IN VARCHAR2,
        P_PRECIO      IN NUMBER,
        P_FECHACOMPRA IN DATE,
        P_TIPO        IN VARCHAR2,
        P_DESCRIPCION IN VARCHAR2
    );

    FUNCTION ADMINISTRACION.OBTENER_INVENTARIO_SEDE(P_SEDE IN NUMBER) RETURN SYS_REFCURSOR;

    PROCEDURE ADMINISTRACION.ACTUALIZAR_INVENTARIO(
        P_ID          IN NUMBER,
        P_NOMBRE      IN VARCHAR2,
        P_PRECIO      IN NUMBER,
        P_FECHACOMPRA IN DATE,
        P_TIPO        IN VARCHAR2,
        P_DESCRIPCION IN VARCHAR2
    );

    PROCEDURE ADMINISTRACION.ELIMINAR_INVENTARIO(P_ID IN NUMBER);

    -- CRUD MAQUINAS
    PROCEDURE ADMINISTRACION.REGISTRAR_MAQUINA(
        P_ID     IN NUMBER,
        P_ESTADO IN VARCHAR2
    );

    FUNCTION ADMINISTRACION.OBTENER_MAQUINAS_SEDE(P_SEDE IN NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION ADMINISTRACION.OBTENER_MAQUINA(P_ID IN NUMBER) RETURN SYS_REFCURSOR;

    PROCEDURE ADMINISTRACION.ACTUALIZAR_MAQUINA(
        P_ID          IN NUMBER,
        P_ESTADO      IN VARCHAR2,
        P_DESCRIPCION IN VARCHAR2,
        P_SEDE        IN NUMBER
    );

    PROCEDURE ADMINISTRACION.ELIMINAR_MAQUINA(P_ID IN NUMBER);

    -- CRUD ELEMENTOS
    PROCEDURE ADMINISTRACION.REGISTRAR_ELEMENTO(
        P_ID IN NUMBER
    );

    FUNCTION ADMINISTRACION.OBTENER_ELEMENTOS_SEDE(P_SEDE IN NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION ADMINISTRACION.OBTENER_ELEMENTO(P_ID IN NUMBER) RETURN SYS_REFCURSOR;

    PROCEDURE ADMINISTRACION.ACTUALIZAR_ELEMENTO(
        P_ID          IN NUMBER,
        P_DESCRIPCION IN VARCHAR2
    );

    PROCEDURE ADMINISTRACION.ELIMINAR_ELEMENTO(P_ID IN NUMBER);

    -- CR [CREATE, READ] REGISTRO ENTRADA SALIDA
    PROCEDURE ADMINISTRACION.REGISTRAR_ENTRADA_SALIDA(
        P_PERSONA     IN NUMBER,
        P_ZONA        IN VARCHAR2,
        P_SEDE        IN NUMBER,
        P_FECHA       IN DATE,
        P_HORAENTRADA IN TIMESTAMP,
        P_HORASALIDA  IN TIMESTAMP
    );

    FUNCTION ADMINISTRACION.OBTENER_ENTRADAS_SALIDAS RETURN SYS_REFCURSOR;
    FUNCTION ADMINISTRACION.OBTENER_ENTRADAS_SALIDAS_PERSONA(P_PERSONA IN NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION ADMINISTRACION.OBTENER_ENTRADAS_SALIDAS_ZONA(P_ZONA IN VARCHAR2) RETURN SYS_REFCURSOR;

    -- CR [CREATE, READ] EVENTOS
    PROCEDURE ADMINISTRACION.REGISTRAR_EVENTO(
        P_LIDER       IN NUMBER,
        P_SEDE        IN NUMBER,
        P_NOMBRE      IN VARCHAR2,
        P_FECHAYHORA  IN DATE,
        P_DURACION    IN NUMBER,
        P_ESTADO      IN VARCHAR2,
        P_DESCRIPCION IN VARCHAR2
    );

    FUNCTION ADMINISTRACION.OBTENER_EVENTOS RETURN SYS_REFCURSOR;
    FUNCTION ADMINISTRACION.OBTENER_EVENTO(P_ID IN NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION ADMINISTRACION.OBTENER_EVENTOS_SEDE(P_SEDE IN NUMBER) RETURN SYS_REFCURSOR;

    -- CR [CREATE, READ] ASISTENTES
    PROCEDURE ADMINISTRACION.REGISTRAR_ASISTENTE(
        P_USUARIO IN NUMBER,
        P_EVENTO  IN NUMBER
    );

    FUNCTION ADMINISTRACION.OBTENER_ASISTENTES_EVENTO(P_EVENTO IN NUMBER) RETURN SYS_REFCURSOR;

    -- R [READ] CONTRATOS
    FUNCTION ADMINISTRACION.OBTENER_CONTRATOS RETURN SYS_REFCURSOR;
    FUNCTION ADMINISTRACION.OBTENER_CONTRATO(P_ID IN NUMBER) RETURN SYS_REFCURSOR;

    -- R [READ] EMPLEADOS
    FUNCTION ADMINISTRACION.OBTENER_EMPLEADOS_SEDE(P_SEDE IN NUMBER) RETURN SYS_REFCURSOR;
END;

CREATE PACKAGE RECEPCION.PKG_RECEPCION AS
    -- CRUD USUARIOS
    PROCEDURE RECEPCION.REGISTRAR_USUARIO(
        P_DOCUMENTO       IN NUMBER,
        P_TIPODOCUMENTO   IN VARCHAR2,
        P_CORREO          IN VARCHAR2,
        P_TELEFONO        IN VARCHAR2,
        P_FECHANACIMIENTO IN DATE,
        P_NOMBRE          IN VARCHAR2,
        P_APELLIDO        IN VARCHAR2,
        P_GENERO          IN VARCHAR2,
        P_EDAD            IN NUMBER
    );

    FUNCTION RECEPCION.OBTENER_USUARIOS RETURN SYS_REFCURSOR;
    FUNCTION RECEPCION.OBTENER_USUARIO(P_DOCUMENTO IN NUMBER) RETURN SYS_REFCURSOR;

    PROCEDURE RECEPCION.ACTUALIZAR_USUARIO(
        P_DOCUMENTO       IN NUMBER,
        P_TIPODOCUMENTO   IN VARCHAR2,
        P_CORREO          IN VARCHAR2,
        P_TELEFONO        IN VARCHAR2,
        P_FECHANACIMIENTO IN DATE,
        P_NOMBRE          IN VARCHAR2,
        P_APELLIDO        IN VARCHAR2,
        P_GENERO          IN VARCHAR2,
        P_EDAD            IN NUMBER
    );

    PROCEDURE RECEPCION.ELIMINAR_USUARIO(P_DOCUMENTO IN NUMBER);

    -- CR [CREATE, READ] MEMBRESIAS
    PROCEDURE RECEPCION.REGISTRAR_MEMBRESIA(
        P_USUARIO    IN NUMBER,
        P_TIPO       IN VARCHAR2,
        P_FACTURA    IN NUMBER,
        P_ESTATUS    IN VARCHAR2,
        P_METODOPAGO IN VARCHAR2,
        P_FECHAINICIO IN DATE,
        P_FECHAFINAL  IN DATE
    );

    FUNCTION RECEPCION.OBTENER_MEMBRESIAS RETURN SYS_REFCURSOR;
    FUNCTION RECEPCION.OBTENER_MEMBRESIA(P_ID IN NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION RECEPCION.OBTENER_MEMBRESIAS_USUARIO(P_USUARIO IN NUMBER) RETURN SYS_REFCURSOR;

    -- R [READ] TIPOS DE MEMBRESIA
    FUNCTION RECEPCION.OBTENER_TIPOS_MEMBRESIA RETURN SYS_REFCURSOR;
    FUNCTION RECEPCION.OBTENER_TIPO_MEMBRESIA(P_TIPO IN VARCHAR2) RETURN SYS_REFCURSOR;

    -- R [READ] SEDES
    FUNCTION RECEPCION.OBTENER_SEDES RETURN SYS_REFCURSOR;
    FUNCTION RECEPCION.OBTENER_SEDE(P_ID IN NUMBER) RETURN SYS_REFCURSOR;

    -- R [READ] BENEFICIOS SEDES
    FUNCTION RECEPCION.OBTENER_BENEFICIOS_SEDES RETURN SYS_REFCURSOR;
    FUNCTION RECEPCION.OBTENER_BENEFICIO_SEDE(P_TIPO_MEMBRESIA IN VARCHAR2, P_SEDE IN NUMBER) RETURN SYS_REFCURSOR;

    -- R [READ] ZONAS
    FUNCTION RECEPCION.OBTENER_ZONAS RETURN SYS_REFCURSOR;
    FUNCTION RECEPCION.OBTENER_ZONA(P_NOMBRE IN VARCHAR2) RETURN SYS_REFCURSOR;
    FUNCTION RECEPCION.OBTENER_ZONAS_SEDE(P_SEDE IN NUMBER) RETURN SYS_REFCURSOR;

    -- R [READ] BENEFICIOS ZONAS
    FUNCTION RECEPCION.OBTENER_BENEFICIOS_ZONAS RETURN SYS_REFCURSOR;
    FUNCTION RECEPCION.OBTENER_BENEFICIO_ZONA(P_TIPO_MEMBRESIA IN VARCHAR2, P_ZONA IN VARCHAR2, P_SEDE IN NUMBER) RETURN SYS_REFCURSOR;

    -- R [READ] EVENTOS
    FUNCTION RECEPCION.OBTENER_EVENTOS RETURN SYS_REFCURSOR;
    FUNCTION RECEPCION.OBTENER_EVENTO(P_ID IN NUMBER) RETURN SYS_REFCURSOR;
END;

CREATE PACKAGE USUARIO.PKG_USUARIO AS
    -- CRD CONTROLES
    PROCEDURE USUARIO.REGISTRAR_CONTROL(
        P_USUARIO  IN NUMBER,
        P_FECHA    IN DATE,
        P_PESO     IN NUMBER,
        P_ALTURA   IN NUMBER,
        P_MBICEP   IN NUMBER,
        P_MTRICEP  IN NUMBER,
        P_MTORSO   IN NUMBER,
        P_MABDOMEN IN NUMBER,
        P_IMC      IN NUMBER
    );

    FUNCTION USUARIO.OBTENER_CONTROL(P_USUARIO IN NUMBER) RETURN SYS_REFCURSOR;

    PROCEDURE USUARIO.ELIMINAR_CONTROL(P_USUARIO IN NUMBER);

    -- R EVENTOS
    FUNCTION USUARIO.OBTENER_EVENTOS RETURN SYS_REFCURSOR;
    FUNCTION USUARIO.OBTENER_EVENTO(P_ID IN NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION USUARIO.OBTENER_EVENTOS_SEDE(P_SEDE IN NUMBER) RETURN SYS_REFCURSOR;
END;

CREATE OR REPLACE PACKAGE GERENCIA.PKG_GERENCIA AS

    -- CRUD LUGARES
    PROCEDURE GERENCIA.REGISTRAR_LUGAR(
        P_PAIS         IN VARCHAR2,
        P_REGION       IN VARCHAR2,
        P_CIUDAD       IN VARCHAR2,
        P_DIRECCION    IN VARCHAR2,
        P_DETALLES     IN VARCHAR2,
        P_CODIGOPOSTAL IN VARCHAR2
    );

    FUNCTION GERENCIA.OBTENER_LUGARES RETURN SYS_REFCURSOR;
    FUNCTION GERENCIA.OBTENER_LUGAR(P_ID IN NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION GERENCIA.OBTENER_LUGARES_CIUDAD(P_PAIS IN VARCHAR2, P_REGION IN VARCHAR2, P_CIUDAD IN VARCHAR2) RETURN SYS_REFCURSOR;

    PROCEDURE GERENCIA.ACTUALIZAR_LUGAR(
        P_ID       IN NUMBER,
        P_DETALLES IN VARCHAR2
    );

    PROCEDURE GERENCIA.ELIMINAR_LUGAR(
        P_ID IN NUMBER
    );

    -- CR [CREATE, READ] EMPLEADO
    PROCEDURE GERENCIA.REGISTRAR_EMPLEADO(
        P_DOCUMENTO       IN NUMBER,
        P_TIPODOCUMENTO   IN VARCHAR2,
        P_CORREO          IN VARCHAR2,
        P_TELEFONO        IN VARCHAR2,
        P_FECHANACIMIENTO IN DATE,
        P_NOMBRE          IN VARCHAR2,
        P_APELLIDO        IN VARCHAR2,
        P_GENERO          IN VARCHAR2,
        P_EDAD            IN NUMBER,
        P_SEDE            IN NUMBER,
        P_ESTATUS         IN VARCHAR2,
        P_CARGO           IN VARCHAR2
    );

    FUNCTION GERENCIA.OBTENER_EMPLEADOS RETURN SYS_REFCURSOR;
    FUNCTION GERENCIA.OBTENER_EMPLEADO(P_DOCUMENTO IN NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION GERENCIA.OBTENER_EMPLEADOS_SEDE(P_SEDE IN NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION GERENCIA.OBTENER_EMPLEADOS_ESTATUS(P_ESTATUS IN VARCHAR2) RETURN SYS_REFCURSOR;

    -- CR [CREATE, READ] CONTRATOS
    PROCEDURE GERENCIA.REGISTRAR_CONTRATO(
        P_EMPLEADO     IN NUMBER,
        P_TIPOCONTRATO IN VARCHAR2,
        P_FECHAINICIO  IN DATE,
        P_FECHAFINAL   IN DATE,
        P_SUELDO       IN NUMBER,
        P_DESCRIPCION  IN VARCHAR2,
        P_ESTADO       IN VARCHAR2
    );

    FUNCTION GERENCIA.OBTENER_CONTRATOS RETURN SYS_REFCURSOR;
    FUNCTION GERENCIA.OBTENER_CONTRATO(P_ID IN NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION GERENCIA.OBTENER_CONTRATOS_EMPLEADO(P_EMPLEADO IN NUMBER) RETURN SYS_REFCURSOR;

    -- CR [CREATE, READ] TIPOS DE MEMBRESIA
    PROCEDURE GERENCIA.REGISTRAR_TIPO_MEMBRESIA(
        P_TIPO         IN VARCHAR2,
        P_PRECIO       IN NUMBER,
        P_DURACIONDIAS IN NUMBER,
        P_DESCRIPCION  IN VARCHAR2
    );

    FUNCTION GERENCIA.OBTENER_TIPOS_MEMBRESIA RETURN SYS_REFCURSOR;
    FUNCTION GERENCIA.OBTENER_TIPO_MEMBRESIA(P_TIPO IN VARCHAR2) RETURN SYS_REFCURSOR;

    -- CR [CREATE, READ] BENEFICIOS SEDES
    PROCEDURE GERENCIA.REGISTRAR_BENEFICIO_SEDE(
        P_TIPO_MEMBRESIA IN VARCHAR2,
        P_SEDE           IN NUMBER,
        P_DESCRIPCION    IN VARCHAR2
    );

    FUNCTION GERENCIA.OBTENER_BENEFICIOS_SEDES RETURN SYS_REFCURSOR;

    -- CR [CREATE, READ] BENEFICIOS ZONAS
    PROCEDURE GERENCIA.REGISTRAR_BENEFICIO_ZONA(
        P_TIPO_MEMBRESIA IN VARCHAR2,
        P_ZONA           IN VARCHAR2,
        P_SEDE           IN NUMBER,
        P_DESCRIPCION    IN VARCHAR2
    );

    FUNCTION GERENCIA.OBTENER_BENEFICIOS_ZONAS RETURN SYS_REFCURSOR;
END PKG_GERENCIA;