insert into Gerencia.TIPOMEMBRESIA (TIPO, PRECIO, DURACIONDIAS, DESCRIPCION) values ('MEM_BASICA_1', 50000, 30, 'Duracion un mes, ofrece: tal tal tales');
insert into Gerencia.TIPOMEMBRESIA (TIPO, PRECIO, DURACIONDIAS, DESCRIPCION) values ('MEM_BASICA_2', 60000, 30, 'Duracion un mes, ofrece: mas que la basica 1');
insert into Gerencia.TIPOMEMBRESIA (TIPO, PRECIO, DURACIONDIAS, DESCRIPCION) values ('MEM_PISCINA', 75000, 30, 'Duracion un mes, ofrece: piscina!!');
insert into Gerencia.TIPOMEMBRESIA (TIPO, PRECIO, DURACIONDIAS, DESCRIPCION) values ('MEM_PREMIUM', 90000, 45, 'Duracion un mes y medio, ofrece: mas que la basica 1');
insert into Gerencia.TIPOMEMBRESIA (TIPO, PRECIO, DURACIONDIAS, DESCRIPCION) values ('MEM_FULL', 110000, 60, 'Duracion Dos MESES, ofrece: TODO!');