ALTER TABLE FACTURAS
    ADD CONSTRAINT PK_FACTURAS PRIMARY KEY (ID);

ALTER TABLE TIPOMEMBRESIA
    ADD CONSTRAINT PK_TIPO_MEMBRESIA PRIMARY KEY (TIPO);

ALTER TABLE USUARIOS
    ADD CONSTRAINT PK_USUARIOS PRIMARY KEY (DOCUMENTO);

ALTER TABLE CONTROLES
    ADD CONSTRAINT PK_CONTROLES PRIMARY KEY (USUARIO, FECHA);

ALTER TABLE MEMBRESIAS
    ADD CONSTRAINT PK_MEMBRESIAS PRIMARY KEY (ID);

ALTER TABLE LUGARES
    ADD CONSTRAINT PK_LUGARES PRIMARY KEY (ID);

ALTER TABLE SEDES
    ADD CONSTRAINT PK_SEDES PRIMARY KEY (ID);

ALTER TABLE EMPLEADOS
    ADD CONSTRAINT PK_EMPLEADOS PRIMARY KEY (DOCUMENTO);

ALTER TABLE CONTRATOS
    ADD CONSTRAINT PK_CONTRATOS PRIMARY KEY (ID, EMPLEADO);

ALTER TABLE SOLICITUDES
    ADD CONSTRAINT PK_SOLICITUDES PRIMARY KEY (ID);

ALTER TABLE EVENTO
    ADD CONSTRAINT PK_EVENTO PRIMARY KEY (ID);

ALTER TABLE ASISTENTES
    ADD CONSTRAINT PK_ASISTENTES PRIMARY KEY (USUARIO, EVENTO);

ALTER TABLE ZONAS
    ADD CONSTRAINT PK_ZONAS PRIMARY KEY (NOMBRE, SEDE);

ALTER TABLE REGISTROENTRADASALIDAS
    ADD CONSTRAINT PK_REGISTRO_ENTRADAS PRIMARY KEY (ID);

ALTER TABLE BENEFICIOZONAS
    ADD CONSTRAINT PK_BENEFICIO_ZONAS PRIMARY KEY (TIPO_MEMBRESIA, ZONA, SEDE);

ALTER TABLE BENEFICIOSEDES
    ADD CONSTRAINT PK_BENEFICIO_SEDES PRIMARY KEY (TIPO_MEMBRESIA, SEDE);

ALTER TABLE INVENTARIO
    ADD CONSTRAINT PK_INVENTARIO PRIMARY KEY (ID);

ALTER TABLE MAQUINAS
    ADD CONSTRAINT PK_MAQUINAS PRIMARY KEY (ID);

ALTER TABLE ELEMENTO
    ADD CONSTRAINT PK_ELEMENTO PRIMARY KEY (ID);


ALTER TABLE MEMBRESIAS
    ADD CONSTRAINT UK_UPROPIETARIO_DE_MEMBRESIA UNIQUE (USUARIO);