-- Esquema Gerencia
ALTER TABLE Gerencia.FACTURAS
    ADD CONSTRAINT PK_FACTURAS PRIMARY KEY (ID);

ALTER TABLE Gerencia.TIPOMEMBRESIA
    ADD CONSTRAINT PK_TIPO_MEMBRESIA PRIMARY KEY (TIPO);

ALTER TABLE Gerencia.USUARIOS
    ADD CONSTRAINT PK_USUARIOS PRIMARY KEY (DOCUMENTO);

ALTER TABLE Gerencia.MEMBRESIAS
    ADD CONSTRAINT PK_MEMBRESIAS PRIMARY KEY (ID);

ALTER TABLE Gerencia.LUGARES
    ADD CONSTRAINT PK_LUGARES PRIMARY KEY (ID);

ALTER TABLE Gerencia.SEDES
    ADD CONSTRAINT PK_SEDES PRIMARY KEY (ID);

ALTER TABLE Gerencia.EMPLEADOS
    ADD CONSTRAINT PK_EMPLEADOS PRIMARY KEY (DOCUMENTO);

ALTER TABLE Gerencia.CONTRATOS
    ADD CONSTRAINT PK_CONTRATOS PRIMARY KEY (ID, EMPLEADO);

ALTER TABLE Gerencia.BENEFICIOZONAS
    ADD CONSTRAINT PK_BENEFICIO_ZONAS PRIMARY KEY (TIPO_MEMBRESIA, ZONA, SEDE);

ALTER TABLE Gerencia.BENEFICIOSEDES
    ADD CONSTRAINT PK_BENEFICIO_SEDES PRIMARY KEY (TIPO_MEMBRESIA, SEDE);

ALTER TABLE Gerencia.MEMBRESIAS
    ADD CONSTRAINT UK_UPROPIETARIO_DE_MEMBRESIA UNIQUE (USUARIO);

-- Esquema Administracion
ALTER TABLE Administracion.SOLICITUDES
    ADD CONSTRAINT PK_SOLICITUDES PRIMARY KEY (ID);

ALTER TABLE Administracion.EVENTOS
    ADD CONSTRAINT PK_EVENTO PRIMARY KEY (ID);

ALTER TABLE Administracion.ASISTENTES
    ADD CONSTRAINT PK_ASISTENTES PRIMARY KEY (USUARIO, EVENTO);

ALTER TABLE Administracion.ZONAS
    ADD CONSTRAINT PK_ZONAS PRIMARY KEY (NOMBRE, SEDE);

ALTER TABLE Administracion.REGISTROENTRADASALIDAS
    ADD CONSTRAINT PK_REGISTRO_ENTRADAS PRIMARY KEY (ID);

ALTER TABLE Administracion.INVENTARIO
    ADD CONSTRAINT PK_INVENTARIO PRIMARY KEY (ID);

ALTER TABLE Administracion.MAQUINAS
    ADD CONSTRAINT PK_MAQUINAS PRIMARY KEY (ID);

ALTER TABLE Administracion.ELEMENTOS
    ADD CONSTRAINT PK_ELEMENTO PRIMARY KEY (ID);

--Esqeuma Usuario
ALTER TABLE Usuario.CONTROLES
    ADD CONSTRAINT PK_CONTROLES PRIMARY KEY (USUARIO, FECHA);