-- Esquema Gerencia
ALTER TABLE Gerencia.MEMBRESIAS
    ADD CONSTRAINT FK_MEMBRESIAS_USUARIO FOREIGN KEY (USUARIO) REFERENCES Gerencia.USUARIOS;

ALTER TABLE Gerencia.MEMBRESIAS
    ADD CONSTRAINT FK_MEMBRESIAS_TIPO FOREIGN KEY (TIPO) REFERENCES Gerencia.TIPOMEMBRESIA;

ALTER TABLE Gerencia.MEMBRESIAS
    ADD CONSTRAINT FK_FACTURA_MEMBRESIAS FOREIGN KEY (Factura) REFERENCES Gerencia.FACTURAS;

ALTER TABLE Gerencia.SEDES
    ADD CONSTRAINT FK_SEDES_UBICACION FOREIGN KEY (UBICACION) REFERENCES Gerencia.LUGARES;

ALTER TABLE Gerencia.EMPLEADOS
    ADD CONSTRAINT FK_EMPLEADOS_SEDE FOREIGN KEY (SEDE) REFERENCES Gerencia.SEDES;

ALTER TABLE Gerencia.CONTRATOS
    ADD CONSTRAINT FK_CONTRATOS_EMPLEADO FOREIGN KEY (EMPLEADO) REFERENCES Gerencia.EMPLEADOS;

ALTER TABLE Gerencia.BENEFICIOZONAS
    ADD CONSTRAINT FK_BENEFICIO_ZONAS_TIPO FOREIGN KEY (TIPO_MEMBRESIA) REFERENCES Gerencia.TIPOMEMBRESIA;

ALTER TABLE Gerencia.BENEFICIOZONAS
    ADD CONSTRAINT FK_BENEFICIO_ZONAS_ZONA FOREIGN KEY (ZONA, SEDE) REFERENCES Administracion.ZONAS;

ALTER TABLE Gerencia.BENEFICIOSEDES
    ADD CONSTRAINT FK_BENEFICIO_SEDES_TIPO FOREIGN KEY (TIPO_MEMBRESIA) REFERENCES Gerencia.TIPOMEMBRESIA;

ALTER TABLE Gerencia.BENEFICIOSEDES
    ADD CONSTRAINT FK_BENEFICIO_SEDES_SEDE FOREIGN KEY (SEDE) REFERENCES Gerencia.SEDES;

-- Esquema Administracion
ALTER TABLE Administracion.SOLICITUDES
    ADD CONSTRAINT FK_SOLICITUDES_CREADOR FOREIGN KEY (CREADOR) REFERENCES Gerencia.EMPLEADOS;

ALTER TABLE Administracion.EVENTOS
    ADD CONSTRAINT FK_EVENTO_LIDER FOREIGN KEY (LIDER) REFERENCES Gerencia.EMPLEADOS;

ALTER TABLE Administracion.EVENTOS
    ADD CONSTRAINT FK_EVENTO_SEDE FOREIGN KEY (SEDE) REFERENCES Gerencia.SEDES;

ALTER TABLE Administracion.ASISTENTES
    ADD CONSTRAINT FK_ASISTENTES_USUARIO FOREIGN KEY (USUARIO) REFERENCES Gerencia.USUARIOS;

ALTER TABLE Administracion.ASISTENTES
    ADD CONSTRAINT FK_ASISTENTES_EVENTO FOREIGN KEY (EVENTO) REFERENCES Administracion.EVENTOS;

ALTER TABLE Administracion.REGISTROENTRADASALIDAS
    ADD CONSTRAINT FK_REGISTRO_ENTRADAS_PERSONA FOREIGN KEY (PERSONA) REFERENCES Gerencia.USUARIOS;

ALTER TABLE Administracion.REGISTROENTRADASALIDAS
    ADD CONSTRAINT FK_REGISTRO_ENTRADAS_ZONA FOREIGN KEY (ZONA, SEDE) REFERENCES Administracion.ZONAS;

ALTER TABLE Administracion.INVENTARIO
    ADD CONSTRAINT FK_INVENTARIO_SEDE FOREIGN KEY (SEDE) REFERENCES Gerencia.SEDES;

ALTER TABLE Administracion.MAQUINAS
    ADD CONSTRAINT FK_MAQUINAS_ID FOREIGN KEY (ID) REFERENCES Administracion.INVENTARIO;

ALTER TABLE Administracion.ELEMENTOS
    ADD CONSTRAINT FK_ELEMENTO_ID FOREIGN KEY (ID) REFERENCES Administracion.INVENTARIO;


--Esquema Usuario
ALTER TABLE Usuario.CONTROLES
    ADD CONSTRAINT FK_CONTROLES_USUARIO FOREIGN KEY (USUARIO) REFERENCES Gerencia.USUARIOS;
