--Instancias minimas para el funcionamiento de un gimnacio

INSERT INTO Gerencia.LUGARES (ID, PAIS, REGION, CIUDAD, DIRECCION, DETALLES, CODIGOPOSTAL)
VALUES (0, 'Colombia', 'Cundinamarca', 'Bogota', 'Avenida Jimenez 2-10', 'Gimnacio La Papa', '110011');

INSERT INTO Gerencia.SEDES (ID, NOMBRE, UBICACION)
SELECT 1, 'Gimnacio La Papa', ID  FROM GERENCIA.LUGARES
WHERE DETALLES = 'Gimnacio la Gym La Papa' AND ROWNUM = 1;

INSERT INTO Administracion.ZONAS (NOMBRE, SEDE, DESCRIPCION)
VALUES ('Zona Principal', 1, 'Zona General');
INSERT INTO Administracion.ZONAS (NOMBRE, SEDE, DESCRIPCION)
VALUES ('Zona Piscina', 1, 'Zona con Piscina de 50000L');

INSERT INTO Gerencia.TIPOMEMBRESIA (TIPO, PRECIO, DURACIONDIAS, DESCRIPCION)
VALUES ('MEM_BASICA_1', 50000.00, 30, 'Descripción de Membresia Basica');
INSERT INTO Gerencia.TIPOMEMBRESIA (TIPO, PRECIO, DURACIONDIAS, DESCRIPCION)
VALUES ('MEM_PISCINA_1', 75000.00, 45, 'Descripción de Membresia Basica Piscina');

INSERT INTO Gerencia.BENEFICIOSEDES (TIPO_MEMBRESIA, SEDE, DESCRIPCION)
VALUES ('MEM_BASICA_1', 1, 'Descripcion');
INSERT INTO Gerencia.BENEFICIOSEDES (TIPO_MEMBRESIA, SEDE, DESCRIPCION)
VALUES ('MEM_PISCINA_1', 1, 'Descripcion');

INSERT INTO Gerencia.BENEFICIOZONAS (TIPO_MEMBRESIA, ZONA, SEDE, DESCRIPCION)
VALUES ('MEM_BASICA_1', 'Zona Principal', 1, 'Descripcion');
INSERT INTO Gerencia.BENEFICIOZONAS (TIPO_MEMBRESIA, ZONA, SEDE, DESCRIPCION)
VALUES ('MEM_PISCINA_1', 'Zona Piscina', 1, 'Descripcion');

INSERT INTO Gerencia.EMPLEADOS (DOCUMENTO, TIPODOCUMENTO, CORREO, TELEFONO, FECHANACIMIENTO, NOMBRE, APELLIDO, GENERO, EDAD,
                       SEDE, ESTATUS, CARGO)
VALUES (100000000, 'Cedula', 'juanperez@gmail.com', '3000123456', DATE '2000-01-01', 'Juan', 'Perez', 'Masculino', 23,
        1, 'Activo', 'Operador');
INSERT INTO Gerencia.EMPLEADOS (DOCUMENTO, TIPODOCUMENTO, CORREO, TELEFONO, FECHANACIMIENTO, NOMBRE, APELLIDO, GENERO, EDAD,
                       SEDE, ESTATUS, CARGO)
VALUES (1000000002, 'Pasaporte', 'marialopez@hotmail.com', '3111234567', DATE '1999-02-02', 'Maria', 'Lopez',
        'Femenino', 24, 1, 'Activo', 'Entrenador');

INSERT INTO Gerencia.CONTRATOS (ID, EMPLEADO, TIPOCONTRATO, FECHAINICIO, FECHAFINAL, SUELDO, DESCRIPCION, ESTADO)
SELECT 0, DOCUMENTO, 'Fijo', DATE '2023-01-01', DATE '2024-01-01', 1230000.10, 'descripcion', 'Activo' FROM Gerencia.EMPLEADOS
WHERE NOMBRE = 'Juan' AND APELLIDO = 'Perez';
INSERT INTO Gerencia.CONTRATOS (ID, EMPLEADO, TIPOCONTRATO, FECHAINICIO, FECHAFINAL, SUELDO, DESCRIPCION, ESTADO)
SELECT 0, DOCUMENTO, 'Indefinido', DATE '2022-01-01', null, 123000.10, 'descripcion2', 'Activo' FROM Gerencia.EMPLEADOS
WHERE NOMBRE = 'Maria' AND APELLIDO = 'Lopez';

-- Final de las instancias minimas

INSERT INTO Gerencia.USUARIOS (DOCUMENTO, TIPODOCUMENTO, CORREO, TELEFONO, FECHANACIMIENTO, NOMBRE, APELLIDO, GENERO, EDAD)
VALUES (12345678901234, 'Cedula', 'juan.camargo@gmail.com', 3113732948, DATE '2000-12-23', 'Juan Camargo',
        'Pablo Teheran', 'Masculino', 21);

INSERT INTO Gerencia.MEMBRESIAS (ID, USUARIO, TIPO, FACTURA, ESTATUS, METODOPAGO, FECHAINICIO, FECHAFINAL)
VALUES (0, 12345678901234, 'Basica', 0, 'Activo', 'PSE', DATE '2023-01-01', DATE '2023-02-02');

INSERT INTO Administracion.EVENTOS (ID, LIDER, SEDE, NOMBRE, FECHAYHORA, DURACION, ESTADO, DESCRIPCION) --Evento Vencido
VALUES (1, 1000000002, 1, 'Cardio Intenso', TIMESTAMP '2023-11-30 13:00:00', 2, 'Activo', 'Evento Para Mejorar tu Cardio');
INSERT INTO Administracion.EVENTOS (ID, LIDER, SEDE, NOMBRE, FECHAYHORA, DURACION, ESTADO, DESCRIPCION) --Evento Valido
VALUES (1, 1000000002, 1, 'Cardio Suave', TIMESTAMP '2023-12-31 13:00:00', 2, 'Activo', 'Evento Para Mejorar tu Cardio desde Cero');

INSERT INTO Administracion.EVENTOS (ID, LIDER, SEDE, NOMBRE, FECHAYHORA, DURACION, ESTADO, DESCRIPCION) --Debe dar Error
VALUES (1, 100000000, 1, 'Debe Dar Error', TIMESTAMP '2023-12-31 13:00:00', 2, 'Activo', 'Evento Para Dar Error');
