TRUNCATE TABLE Usuario.CONTROLES;

TRUNCATE TABLE Administracion.SOLICITUDES;
TRUNCATE TABLE Administracion.EVENTOS;
TRUNCATE TABLE Administracion.ASISTENTES;
TRUNCATE TABLE Administracion.ZONAS;
TRUNCATE TABLE Administracion.REGISTROENTRADASALIDAS;
TRUNCATE TABLE Administracion.INVENTARIO;
TRUNCATE TABLE Administracion.MAQUINAS;
TRUNCATE TABLE Administracion.ELEMENTOS;

TRUNCATE TABLE Gerencia.FACTURAS;
TRUNCATE TABLE Gerencia.TIPOMEMBRESIA;
TRUNCATE TABLE Gerencia.MEMBRESIAS;
TRUNCATE TABLE Gerencia.LUGARES;
TRUNCATE TABLE Gerencia.SEDES;
TRUNCATE TABLE Gerencia.EMPLEADOS;
TRUNCATE TABLE Gerencia.CONTRATOS;
TRUNCATE TABLE Gerencia.USUARIOS;
TRUNCATE TABLE Gerencia.BENEFICIOZONAS;
TRUNCATE TABLE Gerencia.BENEFICIOSEDES;


DROP TABLE Usuario.CONTROLES;

DROP TABLE Administracion.SOLICITUDES;
DROP TABLE Administracion.EVENTOS;
DROP TABLE Administracion.ASISTENTES;
DROP TABLE Administracion.ZONAS;
DROP TABLE Administracion.REGISTROENTRADASALIDAS;
DROP TABLE Administracion.INVENTARIO;
DROP TABLE Administracion.MAQUINAS;
DROP TABLE Administracion.ELEMENTOS;

DROP TABLE Gerencia.FACTURAS;
DROP TABLE Gerencia.TIPOMEMBRESIA;
DROP TABLE Gerencia.MEMBRESIAS;
DROP TABLE Gerencia.LUGARES;
DROP TABLE Gerencia.SEDES;
DROP TABLE Gerencia.EMPLEADOS;
DROP TABLE Gerencia.CONTRATOS;
DROP TABLE Gerencia.USUARIOS;
DROP TABLE Gerencia.BENEFICIOZONAS;
DROP TABLE Gerencia.BENEFICIOSEDES;